Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
Metrics/AbcSize:
  Max: 30
Metrics/LineLength:
  Max: 100
AllCops:
  Exclude:
    - db/schema.rb
