version: "3"
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ${DOCKER_DATA_ROOT}/${COMPOSE_PROJECT_NAME}/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "127.0.0.1:${DB_HOST_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
  mail:
    image: schickling/mailcatcher
    restart: always
    ports:
      - "127.0.0.1:1080:1080"
      - "127.0.0.1:1025:1025"

  web:
    depends_on:
      - bundler
    image: ${COMPOSE_PROJECT_NAME}_web
    command: /bin/sh -c "./wait_for && bundle exec rake db:migrate && bundle exec guard -g web -i"
    ports:
      - "3000:3000"
    links:
      - db
      - mail
      - errbit
      - bundler
      - bower
    volumes:
      - .:/app
      - bundle-cache:/bundle
      - ./tmp/export:/tmp/export
      - ./tmp/rake_pids:/tmp/rake_pids
      - bower-lib:/lib/assets/bower_components
      - bower-vendor:/lib/assets/bower_components
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT}
      DOMAIN_NAME: ${DOMAIN_NAME}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ERRBIT_ADRESS: http://errbit:8080
      TRUSTED_IP: 172.19.0.0/8
      PAGER: 'busybox less'
      DEPENDENCY_CHECKLIST: "db:5432 bundler:55555 bower:55555"

  rubocop:
    depends_on:
      - bundler
    image: ${COMPOSE_PROJECT_NAME}_web
    command: /bin/sh -c "./wait_for && bundle exec guard -g rubocop -i"
    links:
      - bundler
    volumes:
      - .:/app
      - bundle-cache:/bundle
    environment:
      DEPENDENCY_CHECKLIST: "bundler:55555"

  test:
    depends_on:
      - bundler
    image: ${COMPOSE_PROJECT_NAME}_web
    command: /bin/sh -c "./wait_for && bundle exec rake db:reset && bundle exec guard -g test -i"
    links:
      - db
      - bundler
      - bower
    volumes:
      - .:/app
      - bundle-cache:/bundle
      - bower-lib:/lib/assets/bower_components
      - bower-vendor:/lib/assets/bower_components
    env_file:
      - ./.env.test
    environment:
      RAILS_ENV: test
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      DEPENDENCY_CHECKLIST: "db:5432 bundler:55555 bower:55555"

  bundler:
    build:
      context: .
    image: ${COMPOSE_PROJECT_NAME}_web
    command: /bin/sh -c "bundle install && sh -c 'nc -l -p 55555 0.0.0.0 &\bundle exec guard -g bundler -i'"
    volumes:
      - .:/app
      - bundle-cache:/bundle

  bower:
    depends_on:
      - bundler
    image: ${COMPOSE_PROJECT_NAME}_web
    command: /bin/sh -c "./wait_for && sh -c 'nc -l -p 55555 0.0.0.0 &\bundle exec guard -g bower -i'"
    links:
      - bundler
    volumes:
      - .:/app
      - bundle-cache:/bundle
      - bower-lib:/lib/assets/bower_components
      - bower-vendor:/lib/assets/bower_components
    environment:
      DEPENDENCY_CHECKLIST: "bundler:55555"

  errbit:
    image: errbit/errbit
    ports:
      - "127.0.0.1:${ERRBIT_HOST_PORT}:8080"
    links:
      - mongodb
    environment:
      ERRBIT_USER_HAS_USERNAME: 'true'
      MONGO_URL: mongodb://mongodb:27017/errbit

  mongodb:
    image: mongo
    ports:
      - "127.0.0.1:${MONGO_HOST_PORT}:27017"
    volumes:
      - ${DOCKER_DATA_ROOT}/${COMPOSE_PROJECT_NAME}/mongo:/data/db

  elasticsearch:
    image: elasticsearch:2-alpine
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      MAX_MAP_COUNT: 262144
      cluster.name: graylog
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
      - ./deps/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  graylog:
    image: graylog2/server
    volumes:
      - ${DOCKER_DATA_ROOT}/${COMPOSE_PROJECT_NAME}/graylog/data/journal:/usr/share/graylog/data/journal
      - ./deps/graylog/contentpacks/filebeat_input.json:/usr/share/graylog/data/contentpacks/filebeat_input.json
      - ./deps/graylog/config/graylog.conf:/usr/share/graylog/data/config/graylog.conf
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"
      - "5044:5044"
      - "5144:5144"

  filebeat:
    image: nguoianphu/docker-filebeat
    volumes:
      - ./deps/filebeat/filebeat.yml:/filebeat.yml
      - ./log:/rails_log
    links:
      - graylog

volumes:
  bundle-cache:
  bower-lib:
  bower-vendor:
  elastic-data:
