#!/bin/sh

: ${SLEEP_LENGTH:=2}

wait_for() {
  while ! nc -z $1 $2; do echo echo Waiting for $1 to listen on $2...; sleep $SLEEP_LENGTH; done
}

for var in $DEPENDENCY_CHECKLIST
do
  host=${var%:*}
  port=${var#*:}
  wait_for $host $port
done
