filebeat.prospectors:
  - input_type: log
    paths:
      - /rails_log/*.json
    json.keys_under_root: true
    json.overwrite_keys: false
    json.add_error_key: true
#  - input_type: log
#    paths:
#      - /rails_log/*.log
#    exclude_files:
#      - /rails_log/test.log
#    multiline.pattern: ^\[
#    multiline.negate: true
#    multiline.match: after
filebeat.registry_file: /var/lib/filebeat/registry
output.logstash:
  hosts: ['graylog:5144']
  index: rails
